=== Azure/Azure-Sentinel/.script/utils/schemas/ARM_DeploymentTemplateSchema.json
{
    "id": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Template",
    "description": "An Azure deployment template",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "JSON schema reference"
        },
        "metadata": {
            "type": "object",
            "description": "Additional unstructured metadata to include with the template deployment.",
            "additionalProperties": true
        },
        "contentVersion": {
            "type": "string",
            "pattern": "(^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$)",
            "description": "A 4 number format for the version number of this template file. For example, 1.0.0.0"
        },
        "variables": {
            "type": "object",
            "description": "Variable definitions"
        },
        "parameters": {
            "type": "object",
            "description": "Input parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/parameter"
            }
        },
        "functions": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/functionNamespace"
            },
            "description": "User defined functions"
        },
        "resources": {
            "type": "array",
            "description": "Collection of resources to be deployed",
            "items": {
                "$ref": "#/definitions/resourceBase"
            }
        },
        "outputs": {
            "type": "object",
            "description": "Output parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/output"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "$schema",
        "contentVersion",
        "resources"
    ],
    "definitions": {
        "ARMResourceBase": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the resource"
                },
                "type": {
                    "type": "string",
                    "description": "Resource type"
                },
                "condition": {
                    "type": ["boolean", "string"],
                    "description": "Condition of the resource"
                },
                "apiVersion": {
                    "type": "string",
                    "description": "API Version of the resource type, optional when apiProfile is used on the template"
                },
                "dependsOn": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "Collection of resources this resource depends on"
                }
            },
            "required": [
                "name",
                "type"
            ]
        },
        "proxyResourceBase": {
            "allOf": [
                {
                    "$ref": "#/definitions/ARMResourceBase"
                },
                {
                    "properties": {
                        "location": {
                            "$ref": "#/definitions/resourceLocations",
                            "description": "Location to deploy resource to"
                        }
                    }
                }
            ]
        },
        "resourceBase": {
            "allOf": [
                {
                    "$ref": "#/definitions/ARMResourceBase"
                },
                {
                    "properties": {
                        "location": {
                            "$ref": "#/definitions/resourceLocations",
                            "description": "Location to deploy resource to"
                        },
                        "tags": {
                            "type": "object",
                            "description": "Name-value pairs to add to the resource"
                        },
                        "copy": {
                            "$ref": "#/definitions/resourceCopy"
                        },
                        "scope": {
                            "type": "string",
                            "description": "Scope for the resource or deployment. Today, this works for two cases: 1) setting the scope for extension resources 2) deploying resources to the tenant scope in non-tenant scope deployments"
                        },
                        "comments": {
                            "type": "string"
                        }
                    }
                }
            ]
        },
        "resourceBaseExternal": {
            "$ref": "#/definitions/resourceBase",
            "required": [
                "plan"
            ]
        },
        "resourceSku": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the sku"
                },
                "tier": {
                    "type": "string",
                    "description": "Tier of the sku"
                },
                "size": {
                    "type": "string",
                    "description": "Size of the sku"
                },
                "family": {
                    "type": "string",
                    "description": "Family of the sku"
                },
                "capacity": {
                    "type": "integer",
                    "description": "Capacity of the sku"
                }
            },
            "required": [
                "name"
            ]
        },
        "resourceCopy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the copy"
                },
                "count": {
                    "oneOf": [
                        {
                            "type": "integer"
                        }
                    ],
                    "description": "Count of the copy"
                },
                "mode": {
                    "type": "string",
                    "enum": [
                        "Parallel",
                        "Serial"
                    ],
                    "description": "The copy mode"
                },
                "batchSize": {
                    "oneOf": [
                        {
                            "type": "integer"
                        }
                    ],
                    "description": "The serial copy batch size"
                }
            }
        },
        "resourceKind": {
            "type": "string",
            "maxLength": 64,
            "pattern": "(^[a-zA-Z0-9_.()-]+$)",
            "description": "Kind of resource"
        },
        "resourcePlan": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the plan"
                },
                "promotionCode": {
                    "type": "string",
                    "description": "Plan promotion code"
                },
                "publisher": {
                    "type": "string",
                    "description": "Name of the publisher"
                },
                "product": {
                    "type": "string",
                    "description": "Name of the product"
                },
                "version": {
                    "type": "string",
                    "description": "Version of the product"
                }
            },
            "required": [
                "name"
            ],
            "description": "Plan of the resource"
        },
        "resourceLocations": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "enum": [
                        "East Asia",
                        "Southeast Asia",
                        "Central US",
                        "East US",
                        "East US 2",
                        "West US",
                        "North Central US",
                        "South Central US",
                        "North Europe",
                        "West Europe",
                        "Japan West",
                        "Japan East",
                        "Brazil South",
                        "Australia East",
                        "Australia Southeast",
                        "Central India",
                        "West India",
                        "South India",
                        "Canada Central",
                        "Canada East",
                        "West Central US",
                        "West US 2",
                        "UK South",
                        "UK West",
                        "Korea Central",
                        "Korea South",
                        "global"
                    ]
                }
            ]
        },
        "functionNamespace": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string",
                    "minLength": 1,
                    "description": "Function namespace"
                },
                "members": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/functionMember"
                    },
                    "description": "Function memebers"
                }
            }
        },
        "functionMember": {
            "type": "object",
            "properties": {
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/functionParameter"
                    },
                    "description": "Function parameters"
                },
                "output": {
                    "$ref": "#/definitions/functionOutput",
                    "description": "Function output"
                }
            }
        },
        "functionParameter": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1,
                    "description": "Function parameter name"
                },
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of function parameter value"
                }
            }
        },
        "functionOutput": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of function output value"
                },
                "value": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Value assigned for function output"
                }
            }
        },
        "parameter": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of input parameter"
                },
                "defaultValue": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Default value to be used if one is not provided"
                },
                "allowedValues": {
                    "type": "array",
                    "description": "Value can only be one of these values"
                },
                "metadata": {
                    "type": "object",
                    "description": "Metadata for the parameter, can be any valid JSON object"
                },
                "minValue": {
                    "type": "integer",
                    "description": "Minimum value for the int type parameter"
                },
                "maxValue": {
                    "type": "integer",
                    "description": "Maximum value for the int type parameter"
                },
                "minLength": {
                    "type": "integer",
                    "description": "Minimum length for the string or array type parameter"
                },
                "maxLength": {
                    "type": "integer",
                    "description": "Maximum length for the string or array type parameter"
                }
            },
            "required": [
                "type"
            ],
            "description": "Input parameter definitions"
        },
        "output": {
            "type": "object",
            "properties": {
                "condition": {
                    "oneOf": [
                        {
                            "type": "boolean"
                        }
                    ],
                    "description": "Condition of the output"
                },
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of output value"
                },
                "value": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Value assigned for output"
                },
                "copy": {
                    "$ref": "#/definitions/outputCopy",
                    "description": "Output copy"
                }
            },
            "required": [
                "type"
            ],
            "description": "Set of output parameters"
        },
        "parameterTypes": {
            "enum": [
                "string",
                "securestring",
                "int",
                "bool",
                "object",
                "secureObject",
                "array",
                "String",
                "Securestring",
                "Int",
                "Bool",
                "Object",
                "SecureObject",
                "Array"
            ]
        },
        "parameterValueTypes": {
            "type": [
                "string",
                "boolean",
                "integer",
                "number",
                "object",
                "array",
                "null"
            ]
        },
        "keyVaultReference": {
            "type": "object",
            "properties": {
                "keyVault": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "required": [
                        "id"
                    ],
                    "additionalProperties": false
                },
                "secretName": {
                    "type": "string",
                    "minLength": 1
                },
                "secretVersion": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "keyVault",
                "secretName"
            ],
            "additionalProperties": false
        },
        "outputCopy": {
            "type": "object",
            "properties": {
                "count": {
                    "oneOf": [
                        {
                            "type": "integer"
                        }
                    ],
                    "description": "Count of the copy"
                },
                "input": {
                    "anyOf": [
                        {
                            "type": [
                                "string",
                                "boolean",
                                "integer",
                                "array",
                                "object",
                                "null"
                            ]
                        }
                    ],
                    "description": "Input of the copy"
                }
            },
            "required": [
                "count",
                "input"
            ],
            "description": "Output copy"
        }
    }
}

=== Azure/Azure-Sentinel/Solutions/SpyCloud Enterprise Protection CCF/Playbooks/SpyCloud_AutomationRules/azuredeploy.json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "metadata": {
        "title": "SpyCloud Enterprise Protection - Automation Rules",
        "description": "Deploys automation rules that trigger the SpyCloud MDE Automation and SpyCloud Conditional Access playbooks when a matching SpyCloud analytic rule creates an incident.",
        "prerequisites": [
            "1. The SpyCloud_MDE_Automation and SpyCloud_Conditional_Access_Playbook playbooks must be deployed in the same resource group.",
            "2. The SpyCloud analytic rules (AR_malware_25, AR_Breached_Users_20) must be deployed to the same Microsoft Sentinel workspace.",
            "3. Microsoft Sentinel must be enabled on the target Log Analytics workspace."
        ],
        "postDeployment": [
            "1. Verify the automation rules are visible in Microsoft Sentinel > Automation.",
            "2. Grant each playbook's Managed Identity the Microsoft Sentinel Responder role if not already done."
        ],
        "lastUpdateTime": "2026-07-15T00:00:00.000Z",
        "entities": [],
        "tags": [ "Automation" ],
        "support": {
            "tier": "Partner",
            "name": "SpyCloud",
            "link": "https://support.spycloud.com"
        },
        "source": {
            "type": "solution",
            "name": "SpyCloud Enterprise Protection"
        },
        "author": {
            "name": "SpyCloud"
        },
        "releaseNotes": [
            {
                "version": "1.0.0",
                "title": "SpyCloud Enterprise Protection - Automation Rules",
                "notes": [ "Initial version" ]
            }
        ]
    },
    "parameters": {
        "Sentinel_Workspace_Resource_Id": {
            "type": "string",
            "metadata": {
                "description": "Full resource ID of the Log Analytics workspace with Microsoft Sentinel enabled (e.g., /subscriptions/.../resourceGroups/.../providers/Microsoft.OperationalInsights/workspaces/...)"
            }
        },
        "MDE_PlaybookName": {
            "type": "string",
            "defaultValue": "SpyCloud_MDE_Automation",
            "metadata": {
                "description": "Name of the SpyCloud_MDE_Automation Logic App"
            }
        },
        "ConditionalAccess_PlaybookName": {
            "type": "string",
            "defaultValue": "SpyCloud_Conditional_Access_Playbook",
            "metadata": {
                "description": "Name of the SpyCloud_Conditional_Access_Playbook Logic App"
            }
        },
        "MalwareAnalyticRuleId": {
            "type": "string",
            "defaultValue": "ead4deed-9d48-4646-aee0-6b46c2dd1ae6",
            "metadata": {
                "description": "GUID of the SpyCloud infostealer malware credential exposure analytic rule (AR_malware_25) that triggers the MDE automation rule"
            }
        },
        "BreachedUsersAnalyticRuleId": {
            "type": "string",
            "defaultValue": "a25eba0e-ff42-4c97-a379-d76bdb2aa1e3",
            "metadata": {
                "description": "GUID of the SpyCloud plaintext credential exposure analytic rule (AR_Breached_Users_20) that triggers the Conditional Access automation rule"
            }
        },
        "MDE_Automation_Rule_Order": {
            "type": "int",
            "defaultValue": 1,
            "metadata": {
                "description": "Execution order of the MDE automation rule (lower = higher priority)"
            }
        },
        "ConditionalAccess_Automation_Rule_Order": {
            "type": "int",
            "defaultValue": 2,
            "metadata": {
                "description": "Execution order of the Conditional Access automation rule (lower = higher priority)"
            }
        }
    },
    "variables": {
        "mdeAutomationRuleName": "[guid('SpyCloud-MDE-Rule', parameters('Sentinel_Workspace_Resource_Id'))]",
        "conditionalAccessAutomationRuleName": "[guid('SpyCloud-ConditionalAccess-Rule', parameters('Sentinel_Workspace_Resource_Id'))]"
    },
    "resources": [
        {
            "type": "Microsoft.SecurityInsights/automationRules",
            "name": "[variables('mdeAutomationRuleName')]",
            "scope": "[parameters('Sentinel_Workspace_Resource_Id')]",
            "apiVersion": "2023-02-01-preview",
            "properties": {
                "displayName": "SpyCloud - Isolate compromised device on malware exposure",
                "order": "[parameters('MDE_Automation_Rule_Order')]",
                "triggeringLogic": {
                    "isEnabled": true,
                    "triggersOn": "Incidents",
                    "triggersWhen": "Created",
                    "conditions": [
                        {
                            "conditionType": "Property",
                            "conditionProperties": {
                                "propertyName": "IncidentRelatedAnalyticRuleIds",
                                "operator": "Contains",
                                "propertyValues": [
                                    "[extensionResourceId(parameters('Sentinel_Workspace_Resource_Id'), 'Microsoft.SecurityInsights/alertRules', parameters('MalwareAnalyticRuleId'))]"
                                ]
                            }
                        }
                    ]
                },
                "actions": [
                    {
                        "order": 1,
                        "actionType": "RunPlaybook",
                        "actionConfiguration": {
                            "logicAppResourceId": "[resourceId('Microsoft.Logic/workflows', parameters('MDE_PlaybookName'))]",
                            "tenantId": "[subscription().tenantId]"
                        }
                    }
                ]
            }
        },
        {
            "type": "Microsoft.SecurityInsights/automationRules",
            "name": "[variables('conditionalAccessAutomationRuleName')]",
            "scope": "[parameters('Sentinel_Workspace_Resource_Id')]",
            "apiVersion": "2023-02-01-preview",
            "properties": {
                "displayName": "SpyCloud - Enforce Conditional Access on credential exposure",
                "order": "[parameters('ConditionalAccess_Automation_Rule_Order')]",
                "triggeringLogic": {
                    "isEnabled": true,
                    "triggersOn": "Incidents",
                    "triggersWhen": "Created",
                    "conditions": [
                        {
                            "conditionType": "Property",
                            "conditionProperties": {
                                "propertyName": "IncidentRelatedAnalyticRuleIds",
                                "operator": "Contains",
                                "propertyValues": [
                                    "[extensionResourceId(parameters('Sentinel_Workspace_Resource_Id'), 'Microsoft.SecurityInsights/alertRules', parameters('BreachedUsersAnalyticRuleId'))]"
                                ]
                            }
                        }
                    ]
                },
                "actions": [
                    {
                        "order": 1,
                        "actionType": "RunPlaybook",
                        "actionConfiguration": {
                            "logicAppResourceId": "[resourceId('Microsoft.Logic/workflows', parameters('ConditionalAccess_PlaybookName'))]",
                            "tenantId": "[subscription().tenantId]"
                        }
                    }
                ]
            }
        }
    ],
    "outputs": {
        "mdeAutomationRuleId": {
            "type": "string",
            "value": "[variables('mdeAutomationRuleName')]"
        },
        "conditionalAccessAutomationRuleId": {
            "type": "string",
            "value": "[variables('conditionalAccessAutomationRuleName')]"
        }
    }
}
