=== Azure/Azure-Sentinel/.script/utils/schemas/ARM_DeploymentTemplateSchema.json
{
    "id": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Template",
    "description": "An Azure deployment template",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "description": "JSON schema reference"
        },
        "metadata": {
            "type": "object",
            "description": "Additional unstructured metadata to include with the template deployment.",
            "additionalProperties": true
        },
        "contentVersion": {
            "type": "string",
            "pattern": "(^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$)",
            "description": "A 4 number format for the version number of this template file. For example, 1.0.0.0"
        },
        "variables": {
            "type": "object",
            "description": "Variable definitions"
        },
        "parameters": {
            "type": "object",
            "description": "Input parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/parameter"
            }
        },
        "functions": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/functionNamespace"
            },
            "description": "User defined functions"
        },
        "resources": {
            "type": "array",
            "description": "Collection of resources to be deployed",
            "items": {
                "$ref": "#/definitions/resourceBase"
            }
        },
        "outputs": {
            "type": "object",
            "description": "Output parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/output"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "$schema",
        "contentVersion",
        "resources"
    ],
    "definitions": {
        "ARMResourceBase": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the resource"
                },
                "type": {
                    "type": "string",
                    "description": "Resource type"
                },
                "condition": {
                    "type": ["boolean", "string"],
                    "description": "Condition of the resource"
                },
                "apiVersion": {
                    "type": "string",
                    "description": "API Version of the resource type, optional when apiProfile is used on the template"
                },
                "dependsOn": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "Collection of resources this resource depends on"
                }
            },
            "required": [
                "name",
                "type"
            ]
        },
        "proxyResourceBase": {
            "allOf": [
                {
                    "$ref": "#/definitions/ARMResourceBase"
                },
                {
                    "properties": {
                        "location": {
                            "$ref": "#/definitions/resourceLocations",
                            "description": "Location to deploy resource to"
                        }
                    }
                }
            ]
        },
        "resourceBase": {
            "allOf": [
                {
                    "$ref": "#/definitions/ARMResourceBase"
                },
                {
                    "properties": {
                        "location": {
                            "$ref": "#/definitions/resourceLocations",
                            "description": "Location to deploy resource to"
                        },
                        "tags": {
                            "type": "object",
                            "description": "Name-value pairs to add to the resource"
                        },
                        "copy": {
                            "$ref": "#/definitions/resourceCopy"
                        },
                        "scope": {
                            "type": "string",
                            "description": "Scope for the resource or deployment. Today, this works for two cases: 1) setting the scope for extension resources 2) deploying resources to the tenant scope in non-tenant scope deployments"
                        },
                        "comments": {
                            "type": "string"
                        }
                    }
                }
            ]
        },
        "resourceBaseExternal": {
            "$ref": "#/definitions/resourceBase",
            "required": [
                "plan"
            ]
        },
        "resourceSku": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the sku"
                },
                "tier": {
                    "type": "string",
                    "description": "Tier of the sku"
                },
                "size": {
                    "type": "string",
                    "description": "Size of the sku"
                },
                "family": {
                    "type": "string",
                    "description": "Family of the sku"
                },
                "capacity": {
                    "type": "integer",
                    "description": "Capacity of the sku"
                }
            },
            "required": [
                "name"
            ]
        },
        "resourceCopy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the copy"
                },
                "count": {
                    "oneOf": [
                        {
                            "type": "integer"
                        }
                    ],
                    "description": "Count of the copy"
                },
                "mode": {
                    "type": "string",
                    "enum": [
                        "Parallel",
                        "Serial"
                    ],
                    "description": "The copy mode"
                },
                "batchSize": {
                    "oneOf": [
                        {
                            "type": "integer"
                        }
                    ],
                    "description": "The serial copy batch size"
                }
            }
        },
        "resourceKind": {
            "type": "string",
            "maxLength": 64,
            "pattern": "(^[a-zA-Z0-9_.()-]+$)",
            "description": "Kind of resource"
        },
        "resourcePlan": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the plan"
                },
                "promotionCode": {
                    "type": "string",
                    "description": "Plan promotion code"
                },
                "publisher": {
                    "type": "string",
                    "description": "Name of the publisher"
                },
                "product": {
                    "type": "string",
                    "description": "Name of the product"
                },
                "version": {
                    "type": "string",
                    "description": "Version of the product"
                }
            },
            "required": [
                "name"
            ],
            "description": "Plan of the resource"
        },
        "resourceLocations": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "enum": [
                        "East Asia",
                        "Southeast Asia",
                        "Central US",
                        "East US",
                        "East US 2",
                        "West US",
                        "North Central US",
                        "South Central US",
                        "North Europe",
                        "West Europe",
                        "Japan West",
                        "Japan East",
                        "Brazil South",
                        "Australia East",
                        "Australia Southeast",
                        "Central India",
                        "West India",
                        "South India",
                        "Canada Central",
                        "Canada East",
                        "West Central US",
                        "West US 2",
                        "UK South",
                        "UK West",
                        "Korea Central",
                        "Korea South",
                        "global"
                    ]
                }
            ]
        },
        "functionNamespace": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string",
                    "minLength": 1,
                    "description": "Function namespace"
                },
                "members": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/functionMember"
                    },
                    "description": "Function memebers"
                }
            }
        },
        "functionMember": {
            "type": "object",
            "properties": {
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/functionParameter"
                    },
                    "description": "Function parameters"
                },
                "output": {
                    "$ref": "#/definitions/functionOutput",
                    "description": "Function output"
                }
            }
        },
        "functionParameter": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1,
                    "description": "Function parameter name"
                },
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of function parameter value"
                }
            }
        },
        "functionOutput": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of function output value"
                },
                "value": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Value assigned for function output"
                }
            }
        },
        "parameter": {
            "type": "object",
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of input parameter"
                },
                "defaultValue": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Default value to be used if one is not provided"
                },
                "allowedValues": {
                    "type": "array",
                    "description": "Value can only be one of these values"
                },
                "metadata": {
                    "type": "object",
                    "description": "Metadata for the parameter, can be any valid JSON object"
                },
                "minValue": {
                    "type": "integer",
                    "description": "Minimum value for the int type parameter"
                },
                "maxValue": {
                    "type": "integer",
                    "description": "Maximum value for the int type parameter"
                },
                "minLength": {
                    "type": "integer",
                    "description": "Minimum length for the string or array type parameter"
                },
                "maxLength": {
                    "type": "integer",
                    "description": "Maximum length for the string or array type parameter"
                }
            },
            "required": [
                "type"
            ],
            "description": "Input parameter definitions"
        },
        "output": {
            "type": "object",
            "properties": {
                "condition": {
                    "oneOf": [
                        {
                            "type": "boolean"
                        }
                    ],
                    "description": "Condition of the output"
                },
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of output value"
                },
                "value": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Value assigned for output"
                },
                "copy": {
                    "$ref": "#/definitions/outputCopy",
                    "description": "Output copy"
                }
            },
            "required": [
                "type"
            ],
            "description": "Set of output parameters"
        },
        "parameterTypes": {
            "enum": [
                "string",
                "securestring",
                "int",
                "bool",
                "object",
                "secureObject",
                "array",
                "String",
                "Securestring",
                "Int",
                "Bool",
                "Object",
                "SecureObject",
                "Array"
            ]
        },
        "parameterValueTypes": {
            "type": [
                "string",
                "boolean",
                "integer",
                "number",
                "object",
                "array",
                "null"
            ]
        },
        "keyVaultReference": {
            "type": "object",
            "properties": {
                "keyVault": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "required": [
                        "id"
                    ],
                    "additionalProperties": false
                },
                "secretName": {
                    "type": "string",
                    "minLength": 1
                },
                "secretVersion": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "keyVault",
                "secretName"
            ],
            "additionalProperties": false
        },
        "outputCopy": {
            "type": "object",
            "properties": {
                "count": {
                    "oneOf": [
                        {
                            "type": "integer"
                        }
                    ],
                    "description": "Count of the copy"
                },
                "input": {
                    "anyOf": [
                        {
                            "type": [
                                "string",
                                "boolean",
                                "integer",
                                "array",
                                "object",
                                "null"
                            ]
                        }
                    ],
                    "description": "Input of the copy"
                }
            },
            "required": [
                "count",
                "input"
            ],
            "description": "Output copy"
        }
    }
}

=== Azure/Azure-Sentinel/Playbooks/2S-Sentinel2MISP/MISP-Forwarder/azuredeploy.json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "metadata": {
        "title": "2S-MISP-Forwarder", 
        "description": "This Playbook will forward selected Threat Intelligence from your Sentinel Workspace to an orchestrator playbook. By default it supports sending filehashes and filenames from Defender 365 'Malware was prevented' alerts.",
        "prerequisites": "1. The webhook URI from the MISP-Orchestrator playbook. 2. Microsoft 365 Defender connector configured.",
        "lastUpdateTime": "2023-08-09T09:51:37Z",
        "tags": ["Microsoft Sentinel", "ThreatIntelligenceIndicator", "MISP"], 
        "support": {
            "tier": "Community"
        },
        "author": {
            "name": "Sopra Steria"
        }
    },
"parameters": {
"PlaybookName": {
"defaultValue": "MISP-Forwarder",
"type": "string"
},
"OrchestratorURI": {
"type": "string",
"metadata": {
    "description": "Enter value for OrchestratorURI"
}
}
},
"variables": {
"azuresentinelConnectionName": "[concat('azuresentinel-', parameters('PlaybookName'))]"
},
"resources": [
{
"properties": {
    "provisioningState": "Succeeded",
    "state": "Enabled",
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "parameters": {
            "$connections": {
            "defaultValue": {},
            "type": "Object"
        },
        "OrchestratorURI": {
            "defaultValue": "[parameters('OrchestratorURI')]",
            "type": "string"
        }
    },
    "triggers": {
        "Microsoft_Sentinel_incident": {
            "type": "ApiConnectionWebhook",
            "inputs": {
                "body": {
                    "callback_url": "@{listCallbackUrl()}"
                },
                "host": {
                    "connection": {
                        "name": "@parameters('$connections')['azuresentinel']['connectionId']"
                    }
                },
                "path": "/incident-creation"
            }
        }
    },
    "actions": {
        "For_each": {
            "foreach": "@variables('EntitiesArray')",
            "actions": {
                "Condition": {
                    "actions": {
                        "HTTP": {
                        "runAfter": {},
                        "type": "Http",
                        "inputs": {
                            "body": "@body('Parse_JSON_2')",
                            "headers": {
                                "IncidentId": "@triggerBody()?['object']?['id']",
                                "IncidentTitle": "@triggerBody()?['object']?['properties']?['title']"
                            },
                            "method": "POST",
                            "uri": "@parameters('OrchestratorURI')"
                        }
                    }
                },
                "runAfter": {
                    "Parse_JSON_2": [
                        "Succeeded"
                    ]
                },
                "expression": {
                    "or": [
                        {
                            "equals": [
                                "@body('Parse_JSON_2')?['kind']",
                                "FileHash"
                            ]
                        },
                        {
                            "equals": [
                                "@body('Parse_Json_2')['kind']",
                                "File"
                            ]
                        }
                    ]
                },
                "type": "If"
            },
            "Parse_JSON_2": {
            "runAfter": {},
            "type": "ParseJson",
            "inputs": {
                "content": "@items('For_each')",
            "schema": {}
        }
    }
},
"runAfter": {
    "Initialize_variable_CurrentEntity": [
        "Succeeded"
    ]
},
"type": "Foreach",
"runtimeConfiguration": {
    "concurrency": {
        "repetitions": 1
    }
}
},
"Initialize_variable_CurrentEntity": {
"runAfter": {
    "Initialize_variable_EntitiesArray": [
        "Succeeded"
    ]
},
"type": "InitializeVariable",
"inputs": {
    "variables": [
        {
            "name": "CurrentEntity",
            "type": "string"
        }
    ]
}
},
"Initialize_variable_EntitiesArray": {
"runAfter": {
    "Parse_JSON": [
        "Succeeded"
    ]
},
"type": "InitializeVariable",
"inputs": {
    "variables": [
        {
            "name": "EntitiesArray",
            "type": "array",
            "value": "@body('Parse_JSON')"
        }
    ]
}
},
"Parse_JSON": {
"runAfter": {},
"type": "ParseJson",
"inputs": {
"content": "@triggerBody()?['object']?['properties']?['relatedEntities']",
"schema": {}
}
}
},
"outputs": {}
},
"parameters": {
"$connections": {
"value": {
"azuresentinel": {
"connectionId": "[resourceId('Microsoft.Web/connections', variables('azuresentinelConnectionName'))]",
"connectionName": "[variables('azuresentinelConnectionName')]",
"id": "[concat('/subscriptions/', subscription().subscriptionId, '/providers/Microsoft.Web/locations/', resourceGroup().location, '/managedApis/azuresentinel')]",
"connectionProperties": {
"authentication": {
"type": "ManagedServiceIdentity"
}
}
}
}
}
}
},
"name": "[parameters('PlaybookName')]",
"type": "Microsoft.Logic/workflows",
"location": "[resourceGroup().location]",
"identity": {
"type": "SystemAssigned"
},
"tags": {
"hidden-SentinelTemplateName": "MISP-Forwarder",
"hidden-SentinelTemplateVersion": "1.0"
},
"apiVersion": "2017-07-01",
"dependsOn": [
"[resourceId('Microsoft.Web/connections', variables('azuresentinelConnectionName'))]"
]
},
{
"type": "Microsoft.Web/connections",
"apiVersion": "2016-06-01",
"name": "[variables('azuresentinelConnectionName')]",
"location": "[resourceGroup().location]",
"kind": "V1",
"properties": {
"displayName": "[variables('azuresentinelConnectionName')]",
"customParameterValues": {},
"parameterValueType": "Alternative",
"api": {
"id": "[concat('/subscriptions/', subscription().subscriptionId, '/providers/Microsoft.Web/locations/', resourceGroup().location, '/managedApis/azuresentinel')]"
}
}
}
]
}

=== Azure/Azure-Sentinel/Solutions/Lookout/Data Connectors/LookoutMRAv2_Table_Only.json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "workspace": {
      "type": "string",
      "defaultValue": "LookoutdemoSentinel",
      "metadata": {
        "description": "Workspace name"
      }
    }
  },
  "variables": {
    "tableName": "LookoutMtdV2_CL"
  },
  "resources": [
    {
      "type": "Microsoft.OperationalInsights/workspaces/tables",
      "apiVersion": "2022-10-01",
      "name": "[concat(parameters('workspace'), '/', variables('tableName'))]",
      "properties": {
        "totalRetentionInDays": 90,
        "plan": "Analytics",
        "schema": {
          "name": "[variables('tableName')]",
          "columns": [
            {
              "name": "TimeGenerated",
              "type": "datetime"
            },
            {
              "name": "RawData",
              "type": "string"
            }
          ]
        }
      }
    }
  ]
}
