=== Azure/Azure-Sentinel/.script/utils/schemas/CrowdstrikeReplicatorV2_ConnectorSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "publisher": {
      "type": "string"
    },
    "descriptionMarkdown": {
      "type": "string"
    },
    "additionalRequirementBanner": {
      "type": "string"
    },
    "graphQueries": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "metricName": {
              "type": "string"
            },
            "legend": {
              "type": "string"
            },
            "baseQuery": {
              "type": "string"
            }
          },
          "required": [
            "metricName",
            "legend",
            "baseQuery"
          ]
        }
      ]
    },
    "sampleQueries": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        }
      ]
    },
    "dataTypes": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        }
      ]
    },
    "connectivityCriterias": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "value": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "type",
            "value"
          ]
        }
      ]
    },
    "availability": {
      "type": "object",
      "properties": {
        "status": {
          "type": "integer"
        },
        "isPreview": {
          "type": "boolean"
        }
      },
      "required": [
        "status",
        "isPreview"
      ]
    },
    "permissions": {
      "type": "object",
      "properties": {
        "resourceProvider": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "provider": {
                  "type": "string"
                },
                "permissionsDisplayText": {
                  "type": "string"
                },
                "providerDisplayName": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "requiredPermissions": {
                  "type": "object",
                  "properties": {
                    "write": {
                      "type": "boolean"
                    },
                    "read": {
                      "type": "boolean"
                    },
                    "delete": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "write",
                    "read",
                    "delete"
                  ]
                }
              },
              "required": [
                "provider",
                "permissionsDisplayText",
                "providerDisplayName",
                "scope",
                "requiredPermissions"
              ]
            },
            {
              "type": "object",
              "properties": {
                "provider": {
                  "type": "string"
                },
                "permissionsDisplayText": {
                  "type": "string"
                },
                "providerDisplayName": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "requiredPermissions": {
                  "type": "object",
                  "properties": {
                    "action": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "action"
                  ]
                }
              },
              "required": [
                "provider",
                "permissionsDisplayText",
                "providerDisplayName",
                "scope",
                "requiredPermissions"
              ]
            }
          ]
        },
        "customs": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "description"
              ]
            },
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "description"
              ]
            }
          ]
        }
      },
      "required": [
        "resourceProvider",
        "customs"
      ]
    },
    "instructionSteps": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "title",
    "publisher",
    "descriptionMarkdown",
    "additionalRequirementBanner",
    "graphQueries",
    "sampleQueries",
    "dataTypes",
    "connectivityCriterias",
    "availability",
    "permissions",
    "instructionSteps"
  ]
}

=== Azure/Azure-Sentinel/Solutions/Trend Micro Apex One/Data Connectors/template_TrendMicro_ApexOneAMA.json
{
    "id": "TrendMicroApexOneAma",
    "title": "[Deprecated] Trend Micro Apex One via AMA",
    "publisher": "Trend Micro",
    "descriptionMarkdown": "The [Trend Micro Apex One](https://www.trendmicro.com/en_us/business/products/user-protection/sps/endpoint.html) data connector provides the capability to ingest [Trend Micro Apex One events](https://aka.ms/sentinel-TrendMicroApex-OneEvents) into Microsoft Sentinel. Refer to [Trend Micro Apex Central](https://aka.ms/sentinel-TrendMicroApex-OneCentral) for more information.",
    "additionalRequirementBanner": "This data connector depends on a parser based on Kusto Function to work as expected [**TMApexOneEvent**](https://aka.ms/sentinel-TMApexOneEvent-parser) which is deployed with the Microsoft Sentinel Solution.",
    "graphQueries": [
        {
            "metricName": "Total data received",
            "legend": "TrendMicroApexOne",
            "baseQuery": "CommonSecurityLog\n |where DeviceVendor =~ 'Trend Micro'\n |where DeviceProduct =~ 'Apex Central'\n  |extend sent_by_ama = column_ifexists('CollectorHostName','')\n |where isnotempty(sent_by_ama)"
        }
    ],
    "sampleQueries": [
        {
            "description" : "All logs",
            "query": "\nTMApexOneEvent\n| sort by TimeGenerated"
        }
    ],
    "dataTypes": [
        {
            "name": "CommonSecurityLog (TrendMicroApexOne)",
            "lastDataReceivedQuery": "CommonSecurityLog\n |where DeviceVendor =~ 'Trend Micro'\n |where DeviceProduct =~ 'Apex Central'\n  |extend sent_by_ama = column_ifexists('CollectorHostName','')\n |where isnotempty(sent_by_ama)\n            | summarize Time = max(TimeGenerated)\n            | where isnotempty(Time)"
        }
    ],
    "connectivityCriterias": [
        {
            "type": "IsConnectedQuery",
            "value": [
                "CommonSecurityLog\n |where DeviceVendor =~ 'Trend Micro'\n |where DeviceProduct =~ 'Apex Central'\n  |extend sent_by_ama = column_ifexists('CollectorHostName','')\n |where isnotempty(sent_by_ama)\n | summarize LastLogReceived = max(TimeGenerated)\n | project IsConnected = LastLogReceived > ago(30d)"
            ]
        }
    ],
    "availability": {
        "status": 1,
        "isPreview": false
    },
    "permissions": {
        "resourceProvider": [
            {
                "provider": "Microsoft.OperationalInsights/workspaces",
                "permissionsDisplayText": "read and write permissions are required.",
                "providerDisplayName": "Workspace",
                "scope": "Workspace",
                "requiredPermissions": {
                    "write": true,
                    "read": true,
                    "delete": true
                }
            },
            {
                "provider": "Microsoft.OperationalInsights/workspaces/sharedKeys",
                "permissionsDisplayText": "read permissions to shared keys for the workspace are required. [See the documentation to learn more about workspace keys](https://docs.microsoft.com/azure/azure-monitor/platform/agent-windows#obtain-workspace-id-and-key).",
                "providerDisplayName": "Keys",
                "scope": "Workspace",
                "requiredPermissions": {
                    "action": true
                }
            }
        ],
		"customs": [
      {
        "description": "To collect data from non-Azure VMs, they must have Azure Arc installed and enabled. [Learn more](https://docs.microsoft.com/azure/azure-monitor/agents/azure-monitor-agent-install?tabs=ARMAgentPowerShell,PowerShellWindows,PowerShellWindowsArc,CLIWindows,CLIWindowsArc)"
      },
      {
        "description": "Common Event Format (CEF) via AMA and Syslog via AMA data connectors must be installed [Learn more](https://learn.microsoft.com/azure/sentinel/connect-cef-ama#open-the-connector-page-and-create-the-dcr)"
      }	  
    ]
    },
    "instructionSteps": [
        {
            "title": "", 
            "description": ">This data connector depends on a parser based on a Kusto Function to work as expected [**TMApexOneEvent**](https://aka.ms/sentinel-TMApexOneEvent-parser) which is deployed with the Microsoft Sentinel Solution.",
            "instructions": [ 
				       {
                    "parameters": {
                        "title": "1. Kindly follow the steps to configure the data connector",
                        "instructionSteps": [
                            {
                                "title": "Step A. Configure the Common Event Format (CEF) via AMA data connector",
                                "description": "_Note:- CEF logs are collected only from Linux Agents_\n\n1. Navigate to Microsoft Sentinel workspace ---> configuration ---> Data connector blade .\n\n2. Search for 'Common Event Format (CEF) via AMA' data connector and open it.\n\n3. Check If there is no existing DCR configured to collect required facility of logs, Create a new DCR (Data Collection Rule)\n\n\t_Note:- It is recommended to install minimum 1.27 version of AMA agent [Learn more](https://learn.microsoft.com/azure/azure-monitor/agents/azure-monitor-agent-manage?tabs=azure-portal ) and ensure there is no duplicate DCR as it can cause log duplicacy_\n\n4. Run the command provided in the CEF via AMA data connector page to configure the CEF collector on the machine",
                                "instructions": [
                                ]
                            },
                            {
                                "title": "Step B. Forward Common Event Format (CEF) logs to Syslog agent",
                                "description": "[Follow these steps](https://docs.trendmicro.com/en-us/enterprise/trend-micro-apex-central-2019-online-help/detections/logs_001/syslog-forwarding.aspx) to configure Apex Central sending alerts via syslog. While configuring, on step 6, select the log format **CEF**.",
                                "instructions": [
                                ]
                            },
							{
								"title": "Step C. Validate connection",
								"description": "Follow the instructions to validate your connectivity:\n\nOpen Log Analytics to check if the logs are received using the CommonSecurityLog schema.\n\nIt may take about 20 minutes until the connection streams data to your workspace.\n\nIf the logs are not received, run the following connectivity validation script:\n\n 1. Make sure that you have Python on your machine using the following command: python -version\n\n2. You must have elevated permissions (sudo) on your machine",
								"instructions": [
									{
										"parameters": {
										"label": "Run the following command to validate your connectivity:",
										"value": "sudo wget -O Sentinel_AMA_troubleshoot.py https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/Syslog/Sentinel_AMA_troubleshoot.py&&sudo python Sentinel_AMA_troubleshoot.py --cef"
										},
										"type": "CopyableLabel"
									}
								]
							}							
                        ]
                    },
                    "type": "InstructionStepsGroup"
                }
            ]    
        },

     
        
        {
            "title": "2. Secure your machine ",
            "description": "Make sure to configure the machine's security according to your organization's security policy\n\n\n[Learn more >](https://aka.ms/SecureCEF)"
        }
    ]
}

=== Azure/Azure-Sentinel/Solutions/VMWareESXi/Data Connectors/Connector_Syslog_VMwareESXi.json
{ 
    "id": "VMwareESXi",
    "title": "[Deprecated] VMware ESXi", 
    "publisher": "VMWare", 
    "descriptionMarkdown": "The [VMware ESXi](https://www.vmware.com/products/esxi-and-esx.html) connector allows you to easily connect your VMWare ESXi logs with Microsoft Sentinel This gives you more insight into your organization's ESXi servers and improves your security operation capabilities.", 
    "additionalRequirementBanner":"These queries are dependent on a parser based on a Kusto Function deployed as part of the solution.",
    "graphQueries": [ 
     { 
         "metricName": "Total data received", 
         "legend": "VMwareESXi", 
         "baseQuery": "VMwareESXi" 
     } 
    ], 
          "sampleQueries": [ 
           { 
               "description" : "Total Events by Log Type", 
               "query": "VMwareESXi \n| summarize count() by ProcessName"    
           },
        {
            "description" : "Top 10 ESXi Hosts Generating Events",
            "query": "VMwareESXi \n | summarize count() by HostName \n | top 10 by count_"  
        }
        ], 
            "dataTypes": [ 
            { 
               "name": "Syslog (VMwareESXi)", 
               "lastDataReceivedQuery": "VMwareESXi \n            | summarize Time = max(TimeGenerated)\n            | where isnotempty(Time)" 
            } 
        ], 
             "connectivityCriterias": [ 
                { 
                    "type": "IsConnectedQuery", 
                    "value": [ 
                    "VMwareESXi \n      | where TimeGenerated > ago(3d)\n   |take 1\n         | project IsConnected = true" 
             ] 
                } 
            ], 
            "availability": { 
            "status": 1,
            "isPreview": false 
            }, 
            "permissions": { 
            "resourceProvider": [ 
                   { 
                       "provider": "Microsoft.OperationalInsights/workspaces", 
                       "permissionsDisplayText": "write permission is required.", 
                       "providerDisplayName": "Workspace", 
                       "scope": "Workspace", 
                       "requiredPermissions": { 
                       "write": true, 
                       "delete": true 
                    } 
                } 
            ],
            "customs": [
                {
                    "name": "VMwareESXi",
                    "description": "must be configured to export logs via Syslog"
                }
            ]
    }, 
            "instructionSteps": [
                { 
                    "title": "", 
                    "description": ">**NOTE:** This data connector depends on a parser based on a Kusto Function to work as expected which is deployed as part of the solution. To view the function code in Log Analytics, open Log Analytics/Microsoft Sentinel Logs blade, click Functions and search for the alias VMwareESXi and load the function code or click [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/VMWareESXi/Parsers/VMwareESXi.yaml), on the second line of the query, enter the hostname(s) of your VMwareESXi device(s) and any other unique identifiers for the logstream. The function usually takes 10-15 minutes to activate after solution installation/update.",
                    "instructions": [ 
                    ]    
                },  
                { 
                    "title": "1. Install and onboard the agent for Linux", 
                    "description": "Typically, you should install the agent on a different computer from the one on which the logs are generated.\n\n>  Syslog logs are collected only from **Linux** agents.", 
                    "instructions": [ 
                        { 
                        "parameters": { 
                        "title": "Choose where to install the agent:", 
            "instructionSteps": [ 
                    { 
                    "title": "Install agent on Azure Linux Virtual Machine", 
                    "description": "Select the machine to install the agent on and then click **Connect**.", 
                    "instructions": [ 
                        { 
                        "parameters": { 
                        "linkType": "InstallAgentOnLinuxVirtualMachine" 
                        }, 
                        "type": "InstallAgent" 
                        } 
                    ]    
                }, 
                    { 
                    "title": "Install agent on a non-Azure Linux Machine", 
                    "description": "Download the agent on the relevant machine and follow the instructions.", 
                    "instructions": [ 
                        { 
                        "parameters": { 
                        "linkType": "InstallAgentOnLinuxNonAzure" 
                        }, 
                        "type": "InstallAgent" 
                        } 
                    ] 
                } 
            ] 
                }, 
                    "type": "InstructionStepsGroup" 
                    } 
                ] 
                    }, 
            { 
                    "title": "2. Configure the logs to be collected", 
                    "description": "Configure the facilities you want to collect and their severities.\n 1. Under workspace advanced settings **Configuration**, select **Data** and then **Syslog**.\n 2. Select **Apply below configuration to my machines** and select the facilities and severities.\n 3.  Click **Save**.",
                    "instructions": [
                        {
                            "parameters": { 
                                "linkType": "OpenSyslogSettings"
                            },
                            "type": "InstallAgent"
                        }
                    ]
                },
            {
                "title": "3. Configure and connect the VMware ESXi",
                "description":"1. Follow these instructions to configure the VMWare ESXi to forward syslog: \n - [VMware ESXi 3.5 and 4.x](https://kb.vmware.com/s/article/1016621) \n - [VMware ESXi 5.0+](https://docs.vmware.com/en/VMware-vSphere/5.5/com.vmware.vsphere.monitoring.doc/GUID-9F67DB52-F469-451F-B6C8-DAE8D95976E7.html)\n2. Use the IP address or hostname for the Linux device with the Linux agent installed as the Destination IP address."
            }
        ]
}
