=== Azure/Azure-Sentinel/.script/utils/schemas/SecurityAlert(OATP)_ConnectorSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "publisher": {
            "type": "string"
        },
        "logo": {
            "type": "string"
        },
        "descriptionMarkdown": {
            "type": "string"
        },
        "graphQueries": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "metricName": {
                            "type": "string"
                        },
                        "legend": {
                            "type": "string"
                        },
                        "baseQuery": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "metricName",
                        "legend",
                        "baseQuery"
                    ]
                }
            ]
        },
        "sampleQueries": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "description": {
                            "type": "string"
                        },
                        "query": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "query"
                    ]
                }
            ]
        },
        "connectivityCriterias": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "type": {
                            "type": "string"
                        },
                        "value": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    },
                    "required": [
                        "type",
                        "value"
                    ]
                }
            ]
        },
        "dataTypes": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "lastDataReceivedQuery": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "name",
                        "lastDataReceivedQuery"
                    ]
                }
            ]
        },
        "availability": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "featureFlag": {
                    "type": "object",
                    "properties": {
                        "feature": {
                            "type": "string"
                        },
                        "featureStates": {
                            "type": "object",
                            "properties": {
                                "1": {
                                    "type": "integer"
                                },
                                "2": {
                                    "type": "integer"
                                },
                                "3": {
                                    "type": "integer"
                                },
                                "4": {
                                    "type": "integer"
                                },
                                "5": {
                                    "type": "integer"
                                }
                            },
                            "required": [
                                "1",
                                "2",
                                "3",
                                "4",
                                "5"
                            ]
                        }
                    },
                    "required": [
                        "feature",
                        "featureStates"
                    ]
                }
            },
            "required": [
                "status",
                "featureFlag"
            ]
        },
        "permissions": {
            "type": "object",
            "properties": {
                "resourceProvider": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "provider": {
                                    "type": "string"
                                },
                                "permissionsDisplayText": {
                                    "type": "string"
                                },
                                "providerDisplayName": {
                                    "type": "string"
                                },
                                "scope": {
                                    "type": "string"
                                },
                                "requiredPermissions": {
                                    "type": "object",
                                    "properties": {
                                        "read": {
                                            "type": "boolean"
                                        },
                                        "write": {
                                            "type": "boolean"
                                        },
                                        "delete": {
                                            "type": "boolean"
                                        }
                                    },
                                    "required": [
                                        "read",
                                        "write",
                                        "delete"
                                    ]
                                }
                            },
                            "required": [
                                "provider",
                                "permissionsDisplayText",
                                "providerDisplayName",
                                "scope",
                                "requiredPermissions"
                            ]
                        }
                    ]
                },
                "tenant": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "licenses": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "required": [
                "resourceProvider",
                "tenant",
                "licenses"
            ]
        },
        "instructionSteps": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "instructions": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "parameters": {
                                            "type": "object",
                                            "properties": {
                                                "connectorKind": {
                                                    "type": "string"
                                                },
                                                "title": {
                                                    "type": "string"
                                                },
                                                "enable": {
                                                    "type": "boolean"
                                                }
                                            },
                                            "required": [
                                                "connectorKind",
                                                "title",
                                                "enable"
                                            ]
                                        },
                                        "type": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "parameters",
                                        "type"
                                    ]
                                }
                            ]
                        }
                    },
                    "required": [
                        "title",
                        "description",
                        "instructions"
                    ]
                }
            ]
        },
        "caseGenerationSteps": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "instructions": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "parameters": {
                                            "type": "object",
                                            "properties": {
                                                "filterProduct": {
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "filterProduct"
                                            ]
                                        },
                                        "type": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "parameters",
                                        "type"
                                    ]
                                }
                            ]
                        }
                    },
                    "required": [
                        "instructions"
                    ]
                }
            ]
        }
    },
    "required": [
        "id",
        "title",
        "publisher",
        "logo",
        "descriptionMarkdown",
        "graphQueries",
        "sampleQueries",
        "connectivityCriterias",
        "dataTypes",
        "availability",
        "permissions",
        "instructionSteps",
        "caseGenerationSteps"
    ]
}

=== Azure/Azure-Sentinel/Solutions/Microsoft Defender for Office 365/Data Connectors/template_OfficeATP.JSON
{
    "id": "OfficeATP",
    "title": "Microsoft Defender for Office 365 (Preview)",
    "publisher": "Microsoft",
    "logo": "Office365Logo.svg",
    "descriptionMarkdown": "Microsoft Defender for Office 365 safeguards your organization against malicious threats posed by email messages, links (URLs) and collaboration tools. By ingesting Microsoft Defender for Office 365 alerts into Microsoft Sentinel, you can incorporate information about email- and URL-based threats into your broader risk analysis and build response scenarios accordingly.\n \nThe following types of alerts will be imported:\n\n-   A potentially malicious URL click was detected \n-   Email messages containing malware removed after delivery\n-   Email messages containing phish URLs removed after delivery\n-   Email reported by user as malware or phish \n-   Suspicious email sending patterns detected \n-   User restricted from sending email \n\nThese alerts can be seen by Office customers in the ** Office Security and Compliance Center**.\n\nFor more information, see the [Microsoft Sentinel documentation](https://go.microsoft.com/fwlink/p/?linkid=2219942&wt.mc_id=sentinel_dataconnectordocs_content_cnl_csasci).",
    "graphQueries": [
        {
            "metricName": "Total data received",
            "legend": "SecurityAlert (Office 365 Advanced Threat Protection)",
            "baseQuery": "SecurityAlert\n| where ProviderName == \"OATP\""
        }
    ],
    "sampleQueries": [
        {
            "description": "Security Alert Logs",
            "query": "SecurityAlert\n| where ProviderName == \"OATP\"\n            | sort by TimeGenerated"
        }
    ],
    "connectivityCriterias": [
        {
            "type": "SentinelKinds",
            "value": [
                "OfficeATP"
            ]
        }
    ],
    "dataTypes": [
        {
            "name": "SecurityAlert (OATP)",
            "lastDataReceivedQuery": "SecurityAlert\n| where ProviderName == \"OATP\"\n            | summarize Time = max(TimeGenerated)\n            | where isnotempty(Time)"
        }
    ],
    "availability": {
        "status": 2,
        "featureFlag": {
            "feature": "OfficeATPConnector",
            "featureStates": {
                "1": 2,
                "2": 2,
                "3": 2,
                "4": 2,
                "5": 2
            }
        }
    },
    "permissions": {
        "resourceProvider": [
            {
                "provider": "Microsoft.OperationalInsights/workspaces",
                "permissionsDisplayText": "read and write permissions.",
                "providerDisplayName": "Workspace",
                "scope": "Workspace",
                "requiredPermissions": {
                    "read": true,
                    "write": true,
                    "delete": true
                }
            }
        ],
        "tenant": [
            "GlobalAdmin",
            "SecurityAdmin"
        ],
        "licenses": [
            "OfficeATP"
        ]
    },
    "instructionSteps": [
        {
            "title": "Connect Microsoft Defender for Office 365 alerts to Microsoft Sentinel",
            "description": "Connecting Microsoft Defender for Office 365 will cause your data that is collected by Microsoft Defender for Office 365 service to be stored and processed in the location that you have configured your Microsoft Sentinel workspace.",
            "instructions": [
                {
                    "parameters": {
                        "connectorKind": "OfficeATP",
                        "title": "Microsoft Defender for Office 365",
                        "enable": true
                    },
                    "type": "SentinelResourceProvider"
                }
            ]
        }
    ],
    "caseGenerationSteps": [
        {
            "instructions": [
                {
                    "parameters": {
                        "filterProduct": "Office 365 Advanced Threat Protection"
                    },
                    "type": "FilterAlert"
                }
            ]
        }
    ]
}
