=== Azure/Azure-Sentinel/.script/utils/schemas/Wiz_ConnectorSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "publisher": {
      "type": "string"
    },
    "descriptionMarkdown": {
      "type": "string"
    },
    "logo": {
      "type": "string"
    },
    "graphQueries": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "metricName": {
              "type": "string"
            },
            "legend": {
              "type": "string"
            },
            "baseQuery": {
              "type": "string"
            }
          },
          "required": [
            "metricName",
            "legend",
            "baseQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "metricName": {
              "type": "string"
            },
            "legend": {
              "type": "string"
            },
            "baseQuery": {
              "type": "string"
            }
          },
          "required": [
            "metricName",
            "legend",
            "baseQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "metricName": {
              "type": "string"
            },
            "legend": {
              "type": "string"
            },
            "baseQuery": {
              "type": "string"
            }
          },
          "required": [
            "metricName",
            "legend",
            "baseQuery"
          ]
        }
      ]
    },
    "sampleQueries": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "query": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "query"
          ]
        }
      ]
    },
    "connectivityCriterias": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "value": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "type",
            "value"
          ]
        }
      ]
    },
    "dataTypes": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "lastDataReceivedQuery": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "lastDataReceivedQuery"
          ]
        }
      ]
    },
    "availability": {
      "type": "object",
      "properties": {
        "status": {
          "type": "integer"
        },
        "isPreview": {
          "type": "boolean"
        }
      },
      "required": [
        "status",
        "isPreview"
      ]
    },
    "permissions": {
      "type": "object",
      "properties": {
        "resourceProvider": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "provider": {
                  "type": "string"
                },
                "permissionsDisplayText": {
                  "type": "string"
                },
                "providerDisplayName": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "requiredPermissions": {
                  "type": "object",
                  "properties": {
                    "write": {
                      "type": "boolean"
                    },
                    "read": {
                      "type": "boolean"
                    },
                    "delete": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "write",
                    "read",
                    "delete"
                  ]
                }
              },
              "required": [
                "provider",
                "permissionsDisplayText",
                "providerDisplayName",
                "scope",
                "requiredPermissions"
              ]
            },
            {
              "type": "object",
              "properties": {
                "provider": {
                  "type": "string"
                },
                "permissionsDisplayText": {
                  "type": "string"
                },
                "providerDisplayName": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "requiredPermissions": {
                  "type": "object",
                  "properties": {
                    "action": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "action"
                  ]
                }
              },
              "required": [
                "provider",
                "permissionsDisplayText",
                "providerDisplayName",
                "scope",
                "requiredPermissions"
              ]
            }
          ]
        },
        "customs": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "description"
              ]
            },
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "description"
              ]
            }
          ]
        }
      },
      "required": [
        "resourceProvider",
        "customs"
      ]
    },
    "instructionSteps": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            }
          },
          "required": [
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "title"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "instructions": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "parameters": {
                      "type": "object",
                      "properties": {
                        "fillWith": {
                          "type": "array",
                          "items": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "label": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "fillWith",
                        "label"
                      ]
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "parameters",
                    "type"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "parameters": {
                      "type": "object",
                      "properties": {
                        "fillWith": {
                          "type": "array",
                          "items": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "label": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "fillWith",
                        "label"
                      ]
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "parameters",
                    "type"
                  ]
                }
              ]
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "instructions",
            "title"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "title"
          ]
        },
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "description",
            "title"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "title",
    "publisher",
    "descriptionMarkdown",
    "logo",
    "graphQueries",
    "sampleQueries",
    "connectivityCriterias",
    "dataTypes",
    "availability",
    "permissions",
    "instructionSteps"
  ]
}

=== Azure/Azure-Sentinel/.script/utils/schemas/AwsS3_ConnectorSchema.json
{
  "id": "string",
  "title": "string",
  "publisher": "string",
  "descriptionMarkdown": "string",
  "logo": "string",
  "graphQueries": [
    {
      "metricName": "string",
      "legend": "string",
      "baseQuery": "string"
    }
  ],
  "sampleQueries": [
    {
      "description": "string",
      "query": "string"
    }
  ],
  "connectivityCriterias": [
    {
      "type": "string",
      "value": ["string"]
    }
  ],
  "dataTypes": [
    {
      "name": "string",
      "lastDataReceivedQuery": "string"
    }
  ],
  "availability": {
    "status": 0,
    "isPreview": false
  },
  "permissions": {
    "resourceProvider": [
      {
        "provider": "string",
        "permissionsDisplayText": "string",
        "providerDisplayName": "string",
        "scope": "string",
        "requiredPermissions": {
          "write": false,
          "delete": false
        }
      }
    ],
    "customs": [
      {
        "name": "string",
        "description": "string"
      }
    ]
  },
  "instructionSteps": [
    {
      "title": "string",
      "description": "string",
      "instructions": [
        {
          "parameters": {
            "fillWith": ["string"],
            "label": "string"
          },
          "type": "CopyableLabel"
        }
      ]
    }
  ]
}
